# Project Information
site_name: Discord Modmail
site_description: A Modmail bot for Discord. Allowing safe moderator conversations with server members one server at a time.
site_url: https://github.com/discord-modmail/modmail

# Repository
repo_name: discord-modmail/modmail
repo_url: https://github.com/discord-modmail/modmail
edit_uri: ''

# Copyright
copyright: Copyright &copy; 2021 Discord Modmail

# Dev Configuration
dev_addr: 127.0.0.1:8008
# Configuration
theme:
  name: material

  # Colorscheme for the docs
  palette:
  - scheme: default
    primary: blue
    accent: blue
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  - scheme: slate
    primary: red
    accent: red
    toggle:
      icon: material/weather-night
      name: Switch to dark mode

  # Enabled mkdocs features for the site
  features:
  - navigation.top
  - navigation.instant
  - search.suggest
  - search.highlight
  icon:
    repo: fontawesome/brands/github-alt
  logo: assets/modmail_no_bg.png
  favicon: assets/favicon.png
  language: en

# Plugins
plugins:
- search
- markdownextradata:
    data: data

# Page tree
nav:
- DiscordModmail: README.md
- contributing.md
- security.md
- changelog.md

# Extensions
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed

# Customization
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/discord-modmail/modmail
  - icon: fontawesome/brands/discord
    link: https://discord.gg/ERteGkedDW
  alternate:
  - link: /
    name: en - English

# Custom css for the site
extra_css:
- css/termynal.css
- css/custom.css

# Custom javascript for the site
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js
