[tool.black]
line-length = 99
target-version = ['py37']
include = '\.pyi?$'


[tool.poetry]
name = 'Modmail'
version = '0.0.1'
description = " A modmail bot for Discord. Python 3.7+ compatiable"
license = 'Proprietary'
authors = [
    'ARU <genericusername414@gmail.com>'
]
maintainers = [
    'ARU <genericusername414@gmail.com>'
]
readme = 'README.md'
repository = 'https://github.com/onerandomusername/modmail'
homepage = 'https://github.com/onerandomusername/modmail'
keywords = ['discord', 'modmail']

packages = [
    {include = "modmail"}
]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = {extras = ["speedups"], version = "^3.7.4"}
colorama = "^0.4.3"
coloredlogs = "^15.0"
"discord.py" = "1.6.0"
pydantic = "^1.8.2"
python-dotenv = ">=0.10.3"
toml = "^0.10.2"


[tool.poetry.dev-dependencies]
black = {version = "=19.10b0", allow-prereleases = true}
pylint = "^2.4"
bandit = "^1.6"
taskipy = "^1.8.1"
pre-commit = "^2.12.1"
flake8 = "^3.8.4"
flake8-annotations = "^2.6.2"
flake8-docstrings = "^1.6.0"
flake8-import-order = "^0.18.1"
flake8-string-format = "^0.3.0"
flake8-tidy-imports = "^4.3.0"
pep8-naming = "^0.11.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
start = "python -m modmail"
lint = "flake8"
pre = "pre-commit run --all-files"
precommit = "pre-commit install"
format = "black ."

[tool.flake8]
max-line-length = 99
docstring-convention="all"
import-order-style="pycharm"
application_import_names="bot"
exclude=".cache,.venv,.git,constants.py"
ignore="""
    B311,W503,E226,S311,T000
    D100,D104,D105,D107,
    D203,D212,D214,D215,
    D301,D302,
    D400,D401,D402,D404,D405,D406,D407,D408,D409,D410,D411,D412,D413,D414,D416,D417,
    ANN002,ANN003,ANN101,ANN102,ANN204,ANN206,
    """
