[bot]
prefix = "?"
log_url_prefix = '/'
database_type = 'mongodb'
owners = ''
enable_plugins = true
enable_eval = true
data_collection = true
multi_bot = false

[bot.activity]
twitch_url = "https://www.twitch.tv/discordmodmail/"

[colors]
main_color = "#7289da"
error_color = "#e74c3c"
recipient_color = "#f1c40f"
mod_color = '#2ecc71'

[channels]
main_category_id = "Modmail"
fallback_category_id = "Fallback Modmail"
log_channel_id = "bot-logs"
mention_channel_id = ''
update_channel_id = "0"

[dev]
log_level = 25  # "NOTICE"

[dev.mode]
production = true

[emoji]
# sent_emoji = "white_heavy_check_mark"
# blocked_emoji = "\\N{NO ENTRY SIGN}"

[internal]

[mention]
alert_on_mention = false
silent_alert_on_mention = false
mention_channel_id = ''

[snippets]
anonymous_snippets = false
use_regex_autotrigger = false

[thread]
anon_reply_without_command = false
reply_without_command = false
plain_reply_without_command = false
mention = "@here"
user_typing = true
mod_typing = false
transfer_reactions = true
contact_silently = false
use_user_id_channel_name = false
account_age = -1
guild_age = -1
mod_tag = ''
show_timestamp = true


[thread.anon]
username = 'Staff Team'
tag = 'Response'

[thread.auto_close]
time = 0
silently = false
response = "This thread has been closed automatically due to inactivity after {timeout}."

[thread.close]
footer = "Replying will create a new thread"
title = "Thread Closed"
response = "{closer.mention} has closed this Modmail thread."
on_leave = false
on_leave_reason = "The recipient has left the server."
self_close_response = "You have closed this Modmail thread."

[thread.confirm_creation]
enabled = false
title = "Confirm thread creation"
response = "React to confirm thread creation which will directly contact the moderators"
accept_emoji = "\\N{WHITE HEAVY CHECK MARK}"
deny_emoji = "\\N{NO ENTRY SIGN}"

[thread.cooldown]
time = 0
embed_title = "Message not sent!"
cooldown_thread_response = "You must wait for {delta} before you can contact me again."

[thread.creation]
response = "The staff team will get back to you as soon as possible."
footer = "Your message has been sent"
title = "Thread Created"

[thread.disabled]
new_title = "Not Delivered"
new_response = "We are not accepting new threads."
new_footer = "Please try again later..."
current_title = "Not Delivered"
current_response = "We are not accepting any messages."
current_footer = "Please try again later..."

[thread.move]
title = "Thread Moved"
notify = false
notify_mods = false
response = "This thread has been moved."

[thread.self_closable]
creation_footer = "Click the lock to close the thread"
enabled = false
lock_emoji = "\\N{LOCK}"

[updates]
disable_autoupdates = false
update_notifications = true
