blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/YJtPqVntqM
    about: Please ask and answer questions here. This is also the place to report security vulnerabilities.
