blank_issues_enabled: true
contact_links:
  - name: Questions, concerns, community?
    url: https://discord.gg/YJtPqVntqM
    about: Please ask and answer questions here. This is also the place to report security vulnerabilities.
