name: "Feature request"
description: Suggest a new feature for the bot and/or website.
labels: ["s: needs triage", "t: feature"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: dropdown
  id: projects
  attributes:
    label: Relevant components
    multiple: true
    description: |
      Is this feature for the bot or the website?
      A bot feature would be like a new command, where a website feature would be additional info or options.
    options:
      - bot
      - website
  validations:
    required: true
- type: textarea
  attributes:
    label: What is the feature?
    description: |
      Please decribe here what feature you would like to see added to the relevant part of this project.
  validations:
    required: true
- type: dropdown
  attributes:
    label: Would you like to implement this yourself?
    description: Please note that higher priority features made be added by maintainers.
    multiple: false
    options:
      - Yes, I'd like to implement this
      - No, someone else can implement it
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      Thanks for filling out this form. We recommend joining the [Discord server](https://discord.gg/3f7jBUXdxw) if you haven't already.
