site_name: Discord Modmail
site_description: A Modmail bot for Discord. Allowing safe moderator conversations with server members one server at a time.
site_url: https://github.com/discord-modmail/modmail

theme:
  name: material
  custom_dir: overrides
  palette:
  - scheme: default
    primary: blue
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - scheme: slate
    primary: blue
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/modmail_no_bg.png
  favicon: img/favicon.png
  language: en

repo_name: discord-modmail/modmail
repo_url: https://github.com/discord-modmail/modmail
edit_uri: ''

plugins:
- search
- markdownextradata:
    data: data

nav:
- DiscordModmail: index.md
- Languages:
  - en: /
- contributing.md
- release-notes.md

markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/discord-modmail/modmail
  - icon: fontawesome/brands/discord
    link: https://discord.gg/ERteGkedDW
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/
  alternate:
  - link: /
    name: en - English

extra_css:
- css/termynal.css
- css/custom.css

extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js
