name: Changelog Entry Check

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, reopened]

jobs:
  check-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies using poetry
        if: steps.python_cache.outputs.cache-hit != 'true'
        run: |
          pip install tomli requests

      - name: Changelog Entry Check for the current PR
        run: |
          python -m scripts.news.check_news_workflow ${{ github.event.pull_request.number }}
