# Github Action Workflow enforcing our changelog style of enforcing PR number.
# credit: https://github.com/psf/black/blob/main/.github/workflows/changelog.yml

name: Changelog Entry Check

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, reopened]

jobs:
  build:
    name: Changelog Entry Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Grep CHANGES.md for PR number
        if: contains(github.event.pull_request.labels.*.name, 'skip changelog') != true
        run: |
          grep -Pz "\((\n\s*)?#${{ github.event.pull_request.number }}(\n\s*)?\)" CHANGELOG.md || \
          (echo "Please add '(#${{ github.event.pull_request.number }})' change line to CHANGELOG.md" && \
          exit 1)
